Squashed 'ffmpeg-subtree/' changes from b033913d1c..c6364b711b
c6364b711b lavfi/vf_tonemap_opencl: fix build
3e580351bc lavfi/vf_scale_vulkan: fix build
bb6d9a0f32 Makefile: avoid cp-ing over existing executable files
c534d9f72a lavc/h264_ps: always include the stop bit in [s|p]ps->data
792a9f2406 lavc/videotoolboxdec: insert emu-prevention bytes for HEVC as well
a465e2c39e lavc/videotoolboxdec: fix writing too many 1 bits for the reserved fields
928b22edfe lavc/videotoolboxdec: fix generating HEVC general_profile_compatibility_flags
686b64e155 lavc/videotoolboxdec: fix escaping sequential zero sequences
dfbc921f9f lavc/videotoolboxdec: warn on nonzero status in the callback
e9107d16f3 lavfi/blockdetect: Remove nop init() function
6e13c30a8f vp9: don't overread by 4 pixels in ff_vp9_avg4_mmxext().
d42b410e05 avutil/csp: create public API for colorspace structs
77b529fbd2 fate/dca: Fix test requirements
bdfe9d5418 tests/Makefile: Add PCM function
f55c91497d avcodec/libaomenc: Expose the allintra usage mode
3a7e9caf92 avcodec/vp9: ipred_hd_16x16_16 avx2 implementation
bdba8ecce2 fate/wavpack: Test APE cuesheet tags
2351212227 fate/wavpack: Avoid temp files
3b770682dd fate/wavpack: Fix test requirements
6d037537c1 avcodec/wavpack: Remove redundant av_channel_layout_uninit()
38ef9cf39e fate/vpx: Remove unused define parameters
120aa6173c fate/opus: Restore fate-opus-(celt|hybrid|silk)
415f012359 avcodec/ffv1enc: Fix undefined left shifts of negative numbers
c5b2ddfe18 avcodec/iff: Remove redundant #if
366ef56f7f avcodec/ffv1enc: Eliminate float/double from find_best_state()
9e4d1549e8 avcodec/pcm-dvdenc: Mark unreachable defaults
a7e0997324 avfilter/af_biquads: refactor some options
525f83becd avfilter: add tiltshelf audio filter
fab9130c7a fate/ffmpeg: Fix test requirements
9fba0b8a8c mfenc: Use dlopen instead of LoadLibrary for loading mfplat.dll
0ea61725b1 swscale/aarch64: add hscale specializations
92ea8e03df checkasm: added additional dstW tests for hscale
950123dc31 avcodec/libaomenc: Add unmet target level warning
93b31dae1d avfilter/af_biquads: fix low/highshelf 'k' calculation
f912cefb83 qsv: check for libmfx.pc instead of mfx.pc
6ec127b223 avfilter/vf_vpp_qsv: set outlink to EOF correctly
0dcbe1c1aa doc/protocols: add details and reformat IPFS section
8a0f7f7bfe doc/protocols: sort IPFS section alphabetically
d84f03609e avformat/matroskadec: assert non NULL buf
7bfbd24e71 Changelog: Add line for IPFS
5982da87e3 avformat/act: Check ff_get_wav_header() for failure
cb5be590cd avformat/jpegxl_probe: Check init_get_bits8() for failure
5d8d3c1ac2 avutil/mem: fix doc for reallocs
3c694967f8 lavc/aarch64: hevc_sao reschedule slightly
1cb601ad10 avcodec/mfenc: Dynamically load MFPlat.DLL
478e1a98a2 qsv: add requirement for the mininal version of libmfx
f8a07c4d4a libavcodec/qsvenc: expose only supported options
cc679054c7 checkasm: improve hevc_sao test
2e832be322 lavc/aarch64: add hevc sao edge 8x8
92f67e4017 lavc/aarch64: add hevc sao edge 16x16
d957ee34a6 lavc/aarch64: fix hevc sao band filter
8d788c567a avcodec/mjpegenc: Remove ineffective pred option
d587b1c323 avcodec/mpegvideoenc: Remove ineffective options
de640d2b53 avcodec/mjpegenc: Remove pointless motion-estimation options
3fba5d4f3c avcodec/mpegvideoenc: Remove ineffective [pb]bias options
49838705a4 avcodec/pthread_frame: Don't update the first thread ctx before freeing
a78173374a ffbuild/common: Fix CPPFLAGS applied for compiling C++ files

git-subtree-dir: ffmpeg-subtree
git-subtree-split: c6364b711bad1fe2fbd90e5b2798f87080ddf5ea

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3130,7 +3130,6 @@ wmv3_vdpau_hwaccel_select="vc1_vdpau_hwaccel"
 
 # hardware-accelerated codecs
 mediafoundation_deps="mftransform_h MFCreateAlignedMemoryBuffer"
-mediafoundation_extralibs="-lmfplat -lmfuuid -lole32 -lstrmiids"
 omx_deps="libdl pthreads"
 omx_rpi_select="omx"
 qsv_deps="libmfx"
@@ -6566,8 +6565,11 @@ enabled liblensfun        && require_pkg_config liblensfun lensfun lensfun.h lf_
 # Media SDK or Intel Media Server Studio, these don't come with
 # pkg-config support.  Instead, users should make sure that the build
 # can find the libraries and headers through other means.
-enabled libmfx            && { check_pkg_config libmfx libmfx "mfx/mfxvideo.h" MFXInit ||
-                               { require libmfx "mfx/mfxvideo.h" MFXInit "-llibmfx $advapi32_extralibs" && warn "using libmfx without pkg-config"; } }
+enabled libmfx            && { check_pkg_config libmfx "libmfx >= 1.28" "mfx/mfxvideo.h" MFXInit ||
+                               { require libmfx "mfx/mfxvideo.h mfx/mfxdefs.h" MFXInit "-llibmfx $advapi32_extralibs" &&
+                                 { test_cpp_condition mfx/mfxdefs.h "MFX_VERSION >= 1028" || die "ERROR: libmfx version must be >= 1.28"; }  &&
+                                 warn "using libmfx without pkg-config"; } }
+
 if enabled libmfx; then
    check_cc MFX_CODEC_VP9 "mfx/mfxvp9.h mfx/mfxstructures.h" "MFX_CODEC_VP9"
 fi
@@ -6875,6 +6877,9 @@ test_cpp <<EOF && enable uwp && d3d11va_extralibs="-ldxgi -ld3d11"
 #error no family set
 #endif
 EOF
+
+# mediafoundation requires linking directly to mfplat if building for uwp target
+enabled uwp && mediafoundation_extralibs="-lmfplat -lmfuuid -lole32 -lstrmiids" || mediafoundation_extralibs="-lmfuuid -lole32 -lstrmiids"
 
 enabled libdrm &&
     check_pkg_config libdrm_getfb2 libdrm "xf86drmMode.h" drmModeGetFB2
